---
title: "Main_Data_Analysis"
author: "Constantinos Yeles"
date: "10/07/2019"
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---
# installation of libraries
```{r install_libraries}
BiocManager::install(c("wesanderson","edgeR","rafalib","derfinderPlot"))

```
# load libraries
```{r load_libraries}
library(tidyverse);library(wesanderson);library(edgeR);library(rafalib);library(lubridate)
suppressPackageStartupMessages(library('derfinder'))
suppressPackageStartupMessages(library('tidyverse'))
suppressPackageStartupMessages(library('wesanderson'))
suppressPackageStartupMessages(library('edgeR'))
suppressPackageStartupMessages(library('rafalib'))
suppressPackageStartupMessages(library('data.table'))
```
# add date
```{r date_of_analysis}
date <- gsub(" ","_",format(Sys.time(), "%b %d %Y"))
```
# import data and make dataframe
```{r create_the_df}
path <- "/home/rstudio/data/GSE63501_16_CTRL_AD"
setwd(path)
smallRNA_files <- dir(path, full.names = TRUE,
                      pattern = "smRNA_gene_expression.xls",
                      recursive = TRUE)
#smallRNA_files <- str_glue("{path}{smallRNA_files}")
#load the list of files in one table
DT <- rbindlist(sapply(smallRNA_files,fread,
                       simplify=FALSE,
                       #select = c(1,2,4,6),
                       verbose=getOption("datatable.verbose", TRUE)),
                use.names= TRUE,idcol="file")  %>%
  rename(smallRNA= "#Gene")

#sep first column to multiple
#  separate("#Gene",c("chr","start","end","strand","smallRNA","DQ"), sep = ":") %>%
#  as_tibble()
#make matrix for DE analysis
dt <- DT %>% group_by(file) %>% select(-RPM) %>%
  spread(key = "file", value = "ReadCount" )
# clean the colnames
names(dt)[3:length(names(dt))] <- names(dt)[3:length(names(dt))] %>%
  str_remove(".+/my_data/") %>%
  str_remove(".trimmed_.+") %>%
  str_replace("^?","S")

names(dt)[3:length(names(dt))] <- names(dt)[3:length(names(dt))] %>%
  str_remove(".+/data/.+AD/") %>%
  str_remove(".trimmed_.+")

targ_path <- dir(pattern = "tex.xls", recursive = TRUE)
#targ_path <- dir(pattern = "Sra", recursive = TRUE)

#targets_file <- fread(targ_path) %>%
#  as_tibble() %>%
#  select(samples,my_col, data_sequenziamento, tissue, total_region, S_P, dev_stage, Reads, Note, Sample_ID, Sex, Years) %>%
#  mutate(my_col = str_replace(my_col,"^?","S"), data_sequenziamento = as.Date(data_sequenziamento,tryFormats = c( "%d/%m/%Y")))

targets_file <- fread(targ_path, select = c("Run","classification")) %>%
  as_tibble() 

target <- match(names(dt),targets_file$Run,nomatch = 0)
#dt1 <- dt
names(dt)[names(dt) %in% targets_file$Run] <- as.character(targets_file$samples[target])
#tibble(names(dt1), names(dt))

writting_path <- str_remove(targ_path,"tex.xls")
writting_path <- str_glue("/home/rstudio/SPAR_data_analysis/results_matrix_{date}_{my_exp}_SPAR.txt")
dt %>% write_tsv(writting_path)
```
# make the dge object and filter for low expressed small RNAs
```{r 1st step preprocessing}
writting_path <- "/home/rstudio/data/GSE63501_16_CTRL_AD/"
my_exp <- "brain_GSE63501"

# Subset the matrix and link the correct names ----
mat <- read_tsv(list.files(pattern = "_SPAR.txt",recursive = TRUE)[1]) %>%
  select(-GeneClass) %>%
  column_to_rownames("smallRNA") %>%
  as.matrix()

targets_file <- targets_file %>%
  filter(tissue %in% c("Brain","Testis"), dev_stage == "Adult",!my_col=="NA")

# filter again for samples with more than one rep ----
reps_samples <- targets_file %>%
  filter(duplicated(total_region)) %>%
  select(total_region) %>%
  distinct()  %>% add_row(total_region = c("Cerebellum", "Cerebellum Right"))

targets_file <- targets_file %>%
  filter(total_region %in% reps_samples$total_region)

mat <- mat[,targets_file$my_col]  

# create df for limma groups ----
group <- as_factor(str_glue("{targets_file$total_region}_{targets_file$tissue}")) %>% 
  str_replace(" ","_")

group <- as_factor(targets_file$classification)

#batch <- as_factor(c(targets_file$Sample_ID[1:29],30:34))
batch <- as_factor(c(targets_file$Sample_ID[1:23],24:length(targets_file$Sample_ID)))

samples <- data.frame(group,batch,row.names = colnames(mat))
samples <- data.frame(group, Run = targets_file$Run, row.names = colnames(mat))

# create the dge object and design ----
x <- DGEList(counts = mat,samples = samples,lib.size = colSums(mat),norm.factors = rep(1,ncol(mat)))
#design <- model.matrix(~0+group+batch)
design <- model.matrix(~group)
colnames(design) <- gsub("group","",colnames(design))
rownames(design) <- rownames(samples)

# filtering ----
keep.exprs1 <- filterByExpr.DGEList(x,design = design)
#keep.exprs2 <- filterByExpr.DGEList(x,group = batch)
x1 <- x[keep.exprs1,,keep.lib.sizes=FALSE]
#x2 <- x[keep.exprs2,,keep.lib.sizes=FALSE]
dim(x);dim(x1)

pal <- wes_palette(length(levels(x1$samples$group)), name = "Darjeeling1", type = "continuous") %>%
  enframe(name = NULL) %>%
  mutate(group = as_factor(levels(x1$samples$group)))

# another pal ----
pal1 <- wes_palette(length(levels(as.factor(targets_file$data_sequenziamento))), name = "Darjeeling1", type = "continuous") %>%
  enframe(name = NULL) %>%
  mutate(
    date_seq = as.factor(levels(as.factor(targets_file$data_sequenziamento))))

# add color to the data x1 ----
x1$colours <- inner_join(x1$samples,pal,by= "group")$value
# col_date <- enframe(as.factor(targets_file$data_sequenziamento), name = NULL, value = "date_seq")  
# x1$col_date <- inner_join(col_date,pal1,by= "date_seq")
```
# make density plot and histogram
```{r 2nd step preprocessing plots}
# prepare data for density plot           ----  
cpm <- cpm(x)
lcpm <- cpm(x,log=TRUE,prior.count=5)
summary(lcpm)
table(rowSums(x$counts==0)==length(colnames(mat)))
table(rowSums(x1$counts==0)==length(colnames(mat)))

L <- mean(x$samples$lib.size)*1e-6
M <- median(x$samples$lib.size)*1e-6
c(L,M);(lcpm.cutoff2 <- log2(10/M + 2/L))

cutoff <- cpm(10,mean(x$samples$lib.size))
lcpm.cutoff <- cpm(10,mean(x$samples$lib.size),log = TRUE, prior.count = 5)

par(mfrow=c(1,2))
samplenames <- x$samples$group
nsamples <- ncol(x)

# density plot it ----
pdf(str_glue("{writting_path}density_plot_{date}_{my_exp}.pdf"))

plot(density(lcpm[,1]), col=x1$colours[1], lwd=2, ylim=c(0,4), las=1,
     main="", xlab="")

title(main="A. Raw data", xlab="Log-cpm")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
 den <- density(lcpm[,i])
 lines(den$x, den$y, col=x1$colours[i], lwd=2)
}
legend("topright", legend = samplenames, text.col=x1$colours, bty="n")

lcpm <- cpm(x1, log=TRUE, prior.count=5)
plot(density(lcpm[,1]), col=x1$colours[1], lwd=2, ylim=c(0,1.5), las=1,
     main="", xlab="")
title(main= str_glue("B. Filtered data, {round(cutoff,2)} cpm"), xlab="Log-cpm")
abline(v=lcpm.cutoff, lty=3)
for (i in 2:nsamples){
   den <- density(lcpm[,i])
   lines(den$x, den$y, col=x1$colours[i], lwd=2)
}
legend("topright", legend = samplenames, text.col=x1$colours, bty="n")
dev.off()
## 2.1.3 histogram ------
AveLogCpm_Raw_Data <- aveLogCPM(x)
AveLogCpm_Filtered_Data <-aveLogCPM(x1)

par(mfrow=c(1,2))

pdf(str_glue("{writting_path}histogram_plot_{date}_{my_exp}.pdf"))
hist(AveLogCpm_Raw_Data)
hist(AveLogCpm_Filtered_Data)
dev.off()
```
# normalization
```{r normalization and boxplot}
x1_TMM <- calcNormFactors(x1, method = "TMM")
x1_TMMwsp <- calcNormFactors(x1, method = "TMMwsp")
x1_voomTMM <- voomWithQualityWeights(x1_TMM,design = design,plot = TRUE)
x1_voomQ <- voomWithQualityWeights(x1,design = design,normalize.method = "quantile",plot = TRUE)

lcpm_TMM <- cpm(x1_TMM,normalized.lib.sizes = TRUE, log=TRUE, prior.count=5)
lcpm_TMMwsp <- cpm(x1_TMMwsp,normalized.lib.sizes = TRUE, log=TRUE, prior.count=5)

cpm_TMM <- cpm(x1_TMM,normalized.lib.sizes = TRUE)
cpm_TMMwsp <- cpm(x1_TMMwsp,normalized.lib.sizes = TRUE)

#write_rds(x1_TMM,str_glue("x1_TMMwzp_{experiment}_{date}.rds"))
#x1_voomTMM <- read_rds("~/Documents/new_analysis_workflow/results_R/results_with_DBs/3_IPP_PIWIL1_all_DBs/x1_voomTMM.rds")
par(mar=c(9,5,1,1))
par(mfrow= c(1,1))
#raw data
lcpm <- cpm(x1,log=TRUE,prior.count=5)

pdf(str_glue("{writting_path}boxplot_TMM_{date}_{my_exp}.pdf"))

boxplot(lcpm, las= 2, col= x1$colours, main="", names=group)
title(main="A. Not Normalized filtered data",ylab="Log-cpm")
#TMM data
boxplot(lcpm_TMM, las=2, col= x1$colours, main="",names=group)
title(main="A. TMM Normalized filtered data",ylab="Log-cpm")
#TMMwsp data
boxplot(lcpm_TMMwsp, las=2, col= x1$colours, main="",names=group)
title(main="A. TMMwsp Normalized filtered data",ylab="Log-cpm")
#x1_voomTMM data
boxplot(x1_voomTMM$E, las=2, col= x1$colours, main="",names=group)
title(main="A. voomTMM Normalized filtered data",ylab="Log-cpm")
#x1_voomQ data
boxplot(x1_voomQ$E, las=2, col= x1$colours, main="",names=group)
title(main="A. voomQ Normalized filtered data",ylab="Log-cpm")
dev.off()
```
# make h-clustering
```{r Hierarchical clustering}

norm_l <- list(
               #"raw" = lcpm,
               "TMM" = lcpm_TMM,
               #"TMMwsp" = lcpm_TMMwsp,
               "voomTMM_QW" = x1_voomTMM$E,
               "voomQ_QW" = x1_voomQ$E)
hc_methods <- c("ward.D2",
                "single",
                "complete",
                "average",
                #"median", "centroid",
                "mcquitty")
l_d <- lapply(norm_l,function(x)dist(t(x)))

l_hc <- sapply(hc_methods, function(x) lapply(l_d, function(y) hclust(y,method = x)))

names(l_hc) <- rep(rownames(l_hc),times = ncol(l_hc))

pdf(str_glue("{writting_path}hierach_clust_plot_{date}_{my_exp}.pdf"))
for (i in seq_along(l_hc)) {
  myplclust(l_hc[[i]],
            lab.col = x1$colours, #x1$colours,pal1$value
            labels = x1_TMM$samples$group,#pal1$group
       xlab = str_glue("{names(l_hc[i])}"),
       main = str_glue("{enframe(l_hc[[i]])$value[7]} - {enframe(l_hc[[i]])$value[5]} - region"))
  legend("topright",
       legend = levels(x1$samples$group),
       fill = levels(as_factor(x1$colours)), #x1$colours  
       bty="n",
       cex = 0.9)
}

#sapply(l_hc,function(x)myplclust(x,lab.col = x1$colours,labels = x1_TMM$samples$group,
#       xlab = str_glue("{names(x)}"), main = str_glue("{enframe(x)$value[7]} - {enframe(x)$value[5]} - region")))

dev.off()

#d <- dist(t(lcpm_TMM))
#par(mar=c(7,3,2,2))
#myplclust(hc,lab.col = x1$colours,labels = x1_TMM$samples$group,
#          xlab = "",main="euclidean-ward.D2 - region")
#myplclust(hc,lab.col = x1$colours,labels = targets_file$Years,
#          xlab = "",main="euclidean-ward.D2 - age")
#myplclust(hc,lab.col = x1$colours,labels = targets_file$data_sequenziamento,
#          xlab = "",main="euclidean-ward.D2 - year of run")

#legend("topright",legend = levels(group),
#       fill = x1$colours,
#       bty="n",
#       cex = 0.6)

```
# make MDS plot
```{r}
par(mfrow=c(1,2))
par(mar=c(6,5,2,1)+ 0.1)

pdf(str_glue("{writting_path}MDS_TMM_{date}_{my_exp}.pdf"))
plotMDS(lcpm_TMM,labels = str_glue("{targets_file$Run}"),
                col=x1_TMM$colours,dim.plot = c(1,2))
legend("topright",
       legend= levels(as_factor(targets_file$classification)),
       fill = levels(as_factor(x1$colours)),
       bty="n",
       cex = 1.5, inset = c(.01,.09) )


plotMDS(lcpm_TMM, labels = str_glue("{targets_file$Run}"),
                col=x1_TMM$colours,dim.plot = c(3,4),main="MDS plot")
dev.off()
```
# make PCA plot
```{r}
library(DESeq2)
# make the Deseq dataset -----
dds <- DESeqDataSetFromMatrix(countData = round(x1$counts),
                              colData = targets_file,
                              design = ~ classification )
dds$classification <- relevel(dds$classification, ref = "Control")

#vst -----
vsd <- vst(dds, blind = FALSE)
head(assay(vsd), 3)
sampleDists <- dist(t(assay(vsd)))
sampleDistMatrix <- as.matrix( sampleDists )
#rlog -----
rld <- rlog(dds, blind = FALSE)

dds1 <- estimateSizeFactors(dds)

# check the transformations -----
df <- bind_rows(
  as_data_frame(log2(counts(dds1, normalized=TRUE)[, 1:2]+1)) %>%
    mutate(transformation = "log2(x + 1)"),
  as_data_frame(assay(vsd)[, 1:2]) %>% mutate(transformation = "vst"),
  as_data_frame(assay(rld)[, 1:2]) %>% mutate(transformation = "rlog"))

colnames(df)[1:2] <- c("x", "y")  

# plot them
ggplot(df, aes(x = x, y = y)) + geom_hex(bins = 80) +
  coord_fixed() + facet_grid( . ~ transformation)  
# PCA -----
pdf(str_glue("{writting_path}PCA_VST_DEseq2_{date}_{my_exp}.pdf"))
DESeq2::plotPCA(vsd, intgroup = "classification")
dev.off()
# MDS -----
mds <- as.data.frame(colData(vsd))  %>%
  cbind(cmdscale(sampleDistMatrix))
ggplot(mds, aes(x = `1`, y = `2`, color = classification)) +
  geom_point(size = 3) + coord_fixed()

```
# DE analysis
```{r}
# DEseq2 ----
dds <- DESeq(dds)
res <- results(dds)
summary(res)
resultsNames(dds)

res_AD_vs_Control <- results(dds, name="classification_AD_vs_Control" , alpha = 0.05) 

res_AD_vs_Control <- res_AD_vs_Control %>% as_tibble(rownames = "GeneID") %>% 
  arrange(padj) %>% 
 # inner_join(genes) %>% 
 # select(GeneID,gene_name, everything()) %>% 
  write_tsv(str_glue("{writting_path}res_AD_vs_Ctrl_DEseq2_{date}_{my_exp}.txt"))

# edgeR  ----


# voom   ----
```



